[profile.default]
solc = "0.8.23"
src = "contracts"
test = "foundry_tests"
libs = ["node_modules", "lib"]
no_match_path = "*/integration/*"
bytecode_hash = "none"
optimizer = true
via_ir = true
optimizer_runs = 1000000
fuzz_runs = 10000
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"